-- Publish a fully rebuilt feature table atomically.
-- Prerequisite: run schedule_risk_feature_calculation.sql in this same session;
-- it creates the temporary table schedule_project_features_build.

SET SCHEDULE_REFRESH_RUN_ID = UUID_STRING();
SET SCHEDULE_REFRESH_STARTED_AT = CURRENT_TIMESTAMP();

CREATE OR REPLACE TRANSIENT TABLE
    <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_PROJECT_FEATURES_NEXT
CLUSTER BY (CustomerName, ProjectID)
AS
SELECT
    b.*,
    $SCHEDULE_REFRESH_RUN_ID::STRING AS RefreshRunId,
    $SCHEDULE_REFRESH_STARTED_AT::TIMESTAMP_TZ AS RefreshStartedAtUtc
FROM schedule_project_features_build b;

-- Fail publication if the build is empty or violates project-key uniqueness.
EXECUTE IMMEDIATE $$
DECLARE
    EMPTY_BUILD EXCEPTION (-20001, 'Schedule feature build produced zero rows.');
    DUPLICATE_KEYS EXCEPTION (-20002, 'Schedule feature build contains duplicate CustomerName + ProjectID keys.');
    BUILD_ROWS NUMBER;
    DUPLICATE_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO :BUILD_ROWS
    FROM <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_PROJECT_FEATURES_NEXT;

    SELECT COUNT(*) INTO :DUPLICATE_COUNT
    FROM (
        SELECT CustomerName, ProjectID
        FROM <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_PROJECT_FEATURES_NEXT
        GROUP BY CustomerName, ProjectID
        HAVING COUNT(*) > 1
    );

    IF (BUILD_ROWS = 0) THEN
        RAISE EMPTY_BUILD;
    END IF;

    IF (DUPLICATE_COUNT > 0) THEN
        RAISE DUPLICATE_KEYS;
    END IF;
END;
$$;

-- First deployment bootstraps CURRENT from NEXT. Later runs preserve CURRENT
-- until the single SWAP statement commits the new complete build.
CREATE TRANSIENT TABLE IF NOT EXISTS
    <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_PROJECT_FEATURES_CURRENT
CLONE <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_PROJECT_FEATURES_NEXT;

ALTER TABLE <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_PROJECT_FEATURES_CURRENT
    SWAP WITH <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_PROJECT_FEATURES_NEXT;

INSERT INTO <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_FEATURE_REFRESH_AUDIT (
    REFRESH_RUN_ID,
    REFRESH_STARTED_AT_UTC,
    REFRESH_PUBLISHED_AT_UTC,
    STATUS,
    BUILD_ROW_COUNT,
    DUPLICATE_PROJECT_KEY_COUNT,
    FEATURE_SCHEMA_VERSION,
    KEYWORD_MANIFEST_VERSION
)
SELECT
    MAX(RefreshRunId),
    MAX(RefreshStartedAtUtc),
    CURRENT_TIMESTAMP(),
    'PUBLISHED',
    COUNT(*),
    0,
    MAX(FeatureSchemaVersion),
    MAX(KeywordManifestVersion)
FROM <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_PROJECT_FEATURES_CURRENT;

DROP TABLE IF EXISTS <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_PROJECT_FEATURES_NEXT;

GRANT SELECT ON TABLE <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_PROJECT_FEATURES_CURRENT
    TO ROLE <SCHEDULE_RISK_INFERENCE_ROLE>;

