-- Schedule Risk Agent feature-store control objects.
-- Replace <ANALYTICS_DATABASE> and role names during deployment review.

CREATE SCHEMA IF NOT EXISTS <ANALYTICS_DATABASE>.ML_FEATURES;

CREATE TABLE IF NOT EXISTS <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_FEATURE_STORE_CONFIG (
    CONFIG_KEY STRING NOT NULL,
    CONFIG_VALUE STRING NOT NULL,
    UPDATED_AT_UTC TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_SCHEDULE_FEATURE_STORE_CONFIG PRIMARY KEY (CONFIG_KEY)
);

MERGE INTO <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_FEATURE_STORE_CONFIG target
USING (
    SELECT column1::STRING AS CONFIG_KEY, column2::STRING AS CONFIG_VALUE
    FROM VALUES
        ('FEATURE_SCHEMA_VERSION', 'schedule-project-features-v1'),
        ('KEYWORD_MANIFEST_VERSION', 'approved-keywords-2026-06-11'),
        ('REFRESH_INTERVAL_HOURS', '6'),
        ('MAX_FEATURE_AGE_HOURS', '24'),
        ('HISTORY_RETENTION_MONTHS', '3')
) source
ON target.CONFIG_KEY = source.CONFIG_KEY
WHEN NOT MATCHED THEN
    INSERT (CONFIG_KEY, CONFIG_VALUE) VALUES (source.CONFIG_KEY, source.CONFIG_VALUE);

CREATE TABLE IF NOT EXISTS <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_FEATURE_REFRESH_AUDIT (
    REFRESH_RUN_ID STRING NOT NULL,
    REFRESH_STARTED_AT_UTC TIMESTAMP_TZ NOT NULL,
    REFRESH_PUBLISHED_AT_UTC TIMESTAMP_TZ,
    STATUS STRING NOT NULL,
    BUILD_ROW_COUNT NUMBER,
    DUPLICATE_PROJECT_KEY_COUNT NUMBER,
    FEATURE_SCHEMA_VERSION STRING,
    KEYWORD_MANIFEST_VERSION STRING,
    ERROR_CODE STRING,
    ERROR_MESSAGE STRING
);

-- SCHEDULE_PROJECT_FEATURES_CURRENT is bootstrapped by the first refresh using
-- CREATE TABLE IF NOT EXISTS ... CLONE. This avoids maintaining a 4,000-column
-- handwritten DDL that could diverge from the generated feature calculation.
--
-- SCHEDULE_PROJECT_FEATURES_HISTORY is created separately by
-- schedule_risk_feature_store_history.sql so history can be disabled without
-- changing current-table publication.

-- Direct access requested for the first architecture version.
-- Replace these placeholders with approved Snowflake roles.
GRANT USAGE ON DATABASE <ANALYTICS_DATABASE> TO ROLE <SCHEDULE_RISK_INFERENCE_ROLE>;
GRANT USAGE ON SCHEMA <ANALYTICS_DATABASE>.ML_FEATURES TO ROLE <SCHEDULE_RISK_INFERENCE_ROLE>;
GRANT SELECT ON TABLE <ANALYTICS_DATABASE>.ML_FEATURES.SCHEDULE_FEATURE_STORE_CONFIG
    TO ROLE <SCHEDULE_RISK_INFERENCE_ROLE>;

